### ISSUE TITLE
Can't install app on my Homey 2

### ISSUE THREAD

**Issue by HaccasDave** [TedTolboom/de.steinel#13]
I have a Steinel XLED home 2 Z-wave Floodlight that I want to control from my Homey. However, I can't get the Steinel app to install. 

- If I go to the website on my PC, search for the app & click install, it says it is trying to install already. 
- If I use the Homey v2 app on my phone, go to More, Apps, Add, I get the '.. app will be installed shortly ' message, but even waiting overnight it doesn't show up. 
- If I go to Devices, Add & search for Steinel, it shows the XLED device but when I try to install, I get an error message. 

I am able to install other apps on my Homey.

Do you have any suggestions for me?

**Comment by TedTolboom** [comment]
@HaccasDave thanks for reporting.
Athom released a change (after the previous Steinel app update) to the app store, that is blocking the app to install.

I just updated the app to v1.0.3 (waiting for Athom's approval), that will fix this issue.

I will close this issue for now. Please re-open if not solved based on the v1.0.3 version.
