### ISSUE TITLE
Dim functionality

### ISSUE THREAD

**Issue by JohanvanZanten** [TedTolboom/de.steinel#3]
As the XLED home 2 and the RS LED D2 are not dimmable, they are both regular onoff devices, as far as I know only the L 810 LED iHF is dimmable

**Comment by TedTolboom** [comment]
Hi Johan,

Thanks for reporting and testing... fixed in the following commit:
https://github.com/TedTolboom/de.steinel/commit/81a33f9080d5ff050dcacca74084a6d73b8d9555
