### ISSUE TITLE
Save settings greyed out and wrong default value

### ISSUE THREAD

**Issue by JohanvanZanten** [TedTolboom/de.steinel#4]
Hi Ted,

possibly found another issue:
![save settings button greyout and wrong default value](https://user-images.githubusercontent.com/17182576/35261588-be37f7ac-0008-11e8-9fe9-1b86bca1fea5.PNG)

the description says it all ;)

**Comment by TedTolboom** [comment]
Hi @JohanvanZanten,

Thanks for reporting. 
Should be fixed by the following commit to the development branch: https://github.com/TedTolboom/de.steinel/commit/e74562e8049ec462e69d03da749f3b2a94330fbf

Please let me know if it has been solved...

**Comment by JohanvanZanten** [comment]
Hi Ted,
Installed the latest dev branch, but it reports as 0.0.1 (instead of 0.0.3) and first save (yes was the save button was not greyed out anymore) but failed with the failure unable to commit settings … after which the save button was greyed out once more .

**Comment by TedTolboom** [comment]
Updated in latest release (to app store)
